name:                homework01
version:             0.1.0.0
github:              "h9h/homework01"
license:             BSD3
author:              "h9h"
maintainer:          "git@h9h.de"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Calculator

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/h9h/homework01#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  homework01-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework01

tests:
  homework01-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework01
    - hspec
    - hspec-contrib 
    - QuickCheck 
    - HUnit
